[package]
name = "sqlx-named"
version = "0.1.0"
edition = "2021"
resolver = "2"

[lib]
proc-macro = true

[dependencies]
indexmap = "2.5"
proc-macro2 = "1.0"
quote = "1.0"
sqlparser = "0.50"
syn = { version = "2.0", features = ["full"] }
